Second/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from Second import settings
from SitePC.views import pageNotFound

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls')),
    path('', include('SitePC.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
handler404 = pageNotFound

SitePC/urls.py
from django.urls import path

from SitePC import views
from SitePC.views import helper, Home, Category, ShowPC, About, RegisterUser, LoginUser, logout_user, Profile, Orders_User

urlpatterns = [
    path('', Home.as_view(), name='home'),
    path('about/', About.as_view(), name='about'),

    path('help/', helper, name='helper'),

    path('login/', LoginUser.as_view(), name='login'),
    path('logout/', logout_user, name='logout'),
    path('register/', RegisterUser.as_view(), name='register'),
    path('profile/', Profile.as_view(), name='profile'),
    path('product/<slug:slug>/', ShowPC.as_view(), name = 'product'),
    path('category/<slug:cat_slug>', Category.as_view(), name='category'),
    path('orders/', Orders_User.as_view(), name='orders'),

    path('reviews/', views.reviews, name='reviews'),

    path('cart_add_order/', views.order_create, name='orders_add'),   #post to add order


]

cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/',
         views.cart_add,
         name='cart_add'),
    path('remove/<int:product_id>/',
         views.cart_remove,
         name='cart_remove'),
]

cart/models.py
from django.db import models

# Create your models here.

SitePC/forms.py
from django import forms
from .models import *

class HelpForm(forms.ModelForm):

    message = forms.CharField(label='Ваше сообщение', widget=forms.TextInput(
        attrs={'class': 'form-control form-control-lg form-input', 'placeholder': 'Ваше сообщение'}))
    class Meta:
        model = Help
        fields = ['message', ]
class ReviewsForm(forms.ModelForm):
    message = forms.CharField(label='Ваш отзыв', widget=forms.Textarea(
        attrs={'class': 'form-control form-control-lg form-input', 'placeholder': 'Ваш отзыв', 'rows':'2', 'cols':'50', 'maxlength':'255'}))
    class Meta:
        model = Reviews
        fields = ['message', ]

cart/forms.py
from django import forms

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1,6)]

class CartAddPCForm(forms.Form):
    quantity = forms.TypedChoiceField(label="Количество", choices=PRODUCT_QUANTITY_CHOICES, coerce=int, widget=forms.NumberInput(
                                attrs={'type':'number', 'class':'col-md-5', 'min':'1', 'max':'5', 'value': '1'}))
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

SitePC/views.py
from urllib import request

from django.contrib.auth import logout, login
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.views import LoginView
from django.core.checks import messages
from django.http import HttpResponse, HttpResponseNotFound, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic import ListView, DetailView, TemplateView, CreateView, UpdateView
from django.urls import reverse_lazy
from django.views import generic
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST


from SitePC.forms import HelpForm, ReviewsForm
from SitePC.models import PC, Orders, Orders_PCs, Reviews, orders_status
from SitePC.models import Category as CategoryModel
from SitePC.utils import DataMixin, menu
from accounts.forms import RegisterUserForm, AuthUserForm, UserUpdateForm
from django.shortcuts import render
from django.contrib.auth.decorators import login_required

from accounts.models import User
from django_currentuser.middleware import (
    get_current_user, get_current_authenticated_user)

from cart.cart import Cart
from cart.forms import CartAddPCForm
from cart.views import cart_search

menu = [{'title': 'О нас', 'url_name': 'about'},
        {'title': 'Отзывы', 'url_name': 'reviews'}]



class Profile(DataMixin, UpdateView):
    form_class = UserUpdateForm
    template_name = "SitePC/profile.html"
    success_url = reverse_lazy('home')

    def get_object(self):
        return get_current_authenticated_user()

    def get_context_data(self, *, object_list=None, **kwargs):

        context = super().get_context_data(**kwargs)
        if len(context['form'].errors) != 0:
            user = get_object_or_404(User, pk=get_current_authenticated_user().id)
            context['user'] = user
            c_def = self.get_user_context(title='Профиль ' + context['user'].email,
                                          user=context['user'])
        else:
            c_def = self.get_user_context(title='Профиль ' + context['user'].email,
                                          user=context['user'])
        return dict(list(context.items()) + list(c_def.items()))


class Home(DataMixin, ListView):
    model = PC
    template_name = "SitePC/index.html"
    context_object_name = 'posts'
    allow_empty = False

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        c_def = self.get_user_context(title='Главная страница')
        return dict(list(context.items()) + list(c_def.items()))

    def get_queryset(self):
        return PC.objects.all()


class Category(DataMixin, ListView):
    model = PC
    template_name = "SitePC/index.html"
    context_object_name = 'posts'
    allow_empty = False

    def get_queryset(self):
        return PC.objects.filter(cat__slug=self.kwargs['cat_slug'])

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        c_def = self.get_user_context(title='Категория - ' + str(context['posts'][0].cat),
                                      cat_selected=context['posts'][0].cat_id)
        return dict(list(context.items()) + list(c_def.items()))


class ShowPC(DataMixin, DetailView):
    model = PC
    template_name = "SitePC/post.html"
    context_object_name = 'post'
    allow_empty = False

    def get_context_data(self, *, object_list=None, **kwargs):
        cart_pc_form = CartAddPCForm()
        context = super().get_context_data(**kwargs)
        key = cart_search(self.request, context['post'].id)
        c_def = self.get_user_context(title='Купить ' + context['post'].title, cat_selected=context['post'].cat_id,
                                      cart_pc_form=cart_pc_form, key=key)
        return dict(list(context.items()) + list(c_def.items()))


class About(DataMixin, TemplateView):
    template_name = "SitePC/about.html"

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        c_def = self.get_user_context(title='О нас')
        return dict(list(context.items()) + list(c_def.items()))


def pageNotFound(request, exception):
    return HttpResponseNotFound('<h1> Страница не найдена </h1>')


class RegisterUser(DataMixin, CreateView):
    form_class = RegisterUserForm
    template_name = 'SitePC/register.html'
    success_url = reverse_lazy('login')

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        c_def = self.get_user_context(title='Регистрация')
        return dict(list(context.items()) + list(c_def.items()))

    def form_valid(self, form):
        user = form.save()
        login(self.request, user)
        return redirect('home')
class LoginUser(DataMixin, LoginView):
    form_class = AuthUserForm
    template_name = 'SitePC/login.html'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        c_def = self.get_user_context(title='Авторизация')
        return dict(list(context.items()) + list(c_def.items()))

    def get_success_url(self):
        return reverse_lazy('home')


def logout_user(request):
    logout(request)
    return redirect('login')


def order_create(request):
    if request.method == 'POST':
        cart = Cart(request)
        user = get_current_user()
        address = request.POST['address']
        total_price = request.POST['total_price']
        order = Orders()
        order.user = user
        order.price = total_price
        order.address = address
        order.status = orders_status.objects.get(pk=1)
        order.save()
        for item in cart:
            Orders_PCs.objects.create(order=order, pc=item['product'], count=item['quantity'])
        Cart.clear(request)
        return redirect('orders')


class Orders_User(DataMixin, ListView):
    model = Orders
    template_name = "SitePC/orders.html"
    context_object_name = 'orders'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        all_Orders_PCS = Orders_PCs.objects.filter()
        c_def = self.get_user_context(title='Ваши заказы', all_Orders_PCS=all_Orders_PCS)
        return dict(list(context.items()) + list(c_def.items()))

    def get_queryset(self):
        user = get_current_user()
        orders_user = Orders.objects.filter(user=user)
        return orders_user

def helper(request, **kwargs):
    success = 0
    context = kwargs
    cats = CategoryModel.objects.all()
    context['cats'] = cats
    if 'cat_selected' not in context:
        context['cat_selected'] = 0
    if request.method == 'POST':
        form = HelpForm(request.POST)
        if form.is_valid():
            try:
                help = form.save(commit=False)
                help.user = get_current_user()
                help.save()
                success = 1
            except:
                form.add_error(None, 'Ошибка обращения')
    else:
        form = HelpForm()

    return render(request, 'SitePC/help.html', {'form':form, 'success':success, 'cats':cats, 'menu':menu})

def reviews(request, **kwargs):
    context = kwargs
    cats = CategoryModel.objects.all()
    context['cats'] = cats
    if 'cat_selected' not in context:
        context['cat_selected'] = 0
    user = get_current_authenticated_user()
    orders = Orders.objects.filter(user=user)

    if request.method == 'POST':
        form = ReviewsForm(request.POST)
        if form.is_valid():
            try:
                if request.POST.get('rating') is None:
                    rating = 5
                else:
                    rating = request.POST.get('rating')
                review = form.save(commit=False)
                review.user = get_current_user()
                review.grade = rating
                review.save()
            except:
                form.add_error(None, 'Ошибка добавления отзыва')
    else:
        form = ReviewsForm()
    rating = request.POST.get('rating')
    rev = Reviews.objects.all().order_by('-date')
    return render(request, 'SitePC/reviews.html', {'form':form, 'cats':cats, 'menu':menu, 'rating':rating, 'reviews':rev, 'count':orders.count()})

cart/views.py
from urllib import request

from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from django.views.generic import TemplateView
from django_currentuser.middleware import get_current_authenticated_user, get_current_user

from SitePC.forms import HelpForm
from SitePC.models import PC, Category
from accounts.models import User
from .cart import Cart
from .forms import CartAddPCForm
from SitePC.utils import DataMixin

menu = [{'title': 'О нас', 'url_name': 'about'},
        {'title': 'Отзывы', 'url_name': 'reviews'}]

@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(PC, id=product_id)
    form = CartAddPCForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product,
                 quantity=cd['quantity'],
                 update_quantity=cd['update'])
    return redirect('cart:cart_detail')


def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(PC, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')


def cart_detail(request, **kwargs):
    cart = Cart(request)
    len = cart.__len__()
    for item in cart:
        item['update_quantity_form'] = CartAddPCForm(initial={'quantity': item['quantity'],
                                                              'update': True})
    context = kwargs
    cats = Category.objects.all()
    user = get_object_or_404(User, pk=get_current_authenticated_user().id)
    context['user'] = user
    context['menu'] = menu
    context['cats'] = cats
    if 'cat_selected' not in context:
        context['cat_selected'] = 0

    return render(request, 'cart/detail.html', {'cart': cart, 'menu':menu, 'cats':cats, 'title': "Корзина", 'user':user, 'len': len})

def cart_search(request, product_id):
    cart = Cart(request)
    key = cart.search(product_id)
    return key

SitePC/templates/cart/detail.html
{% extends "SitePC/base.html" %}
{% load static %}

{% block title %}
Корзина покупок
{% endblock %}

{% block content %}
{% if len is not 0 %}
<div class="card" style="background-color: #eee; border:none;">
    <div class="card-body">
        <div class="row align-items-center col-md-12 ">
            <div class="col col-md-2">
            </div>
            <div class="col-md-2 d-flex justify-content-center">
                <div class="text-center text-muted">
                    Наименование
                </div>
            </div>
            <div class="col col-md-2 d-flex justify-content-center">
                <div class="text-center text-muted">
                    Краткое описание
                </div>
            </div>
            <div class="col col-md-2 d-flex justify-content-center">
                <div class="text-center text-muted">
                    Количество
                </div>
            </div>
            <div class="col col-md-1 d-flex justify-content-center">
                <div class="text-center text-muted">
                    Стоимость за шт.
                </div>
            </div>
            <div class="col col-md-2 d-flex justify-content-center">
                <div class="text-center text-muted">
                    Итоговая стоимость
                </div>
            </div>
            <div class="col col-md-1 d-flex justify-content-center">
                <div class="text-center text-muted">
                    Удалить из корзины
                </div>
            </div>
        </div>
    </div>
</div>
{% for item in cart %}
{% with product=item.product %}
<div class="card">
    <div class="card-body">
        <div class="row align-items-center col-md-12">
            <div class="col-md-2 justify-content-center">
                <img src="{{ product.photo.url }}"
                     class="img-thumbnail">
            </div>
            <div class="col-md-2 justify-content-center">
                <div class="text-center">{{ product.title }}</div>
            </div>
            <div class="col-md-2 justify-content-center">
                <div class="text-center">
                    {{ product.cpu }}, {{ product.cpu.count_core }} * {{ product.cpu.value }}
                    ГГц,
                    {% if product.count_ram == 1 %}
                    {{ product.ram.memory }}
                    {% else %}
                    {{ product.count_ram }} * {{ product.ram.memory }}
                    {% endif %}
                    ГБ {{ product.ram.type }},
                    {{ product.video }}, SSD
                    {% if product.count_data == 1 %}
                    {{ product.data.memory }}
                    {% else %}
                    {{ product.count_data }} * {{ product.data.memory }}
                    {% endif %}
                    ГБ
                </div>
            </div>

            <div class="col-md-2 justify-content-center">
                <form action="{% url 'cart:cart_add' product.id %}" method="post">
                    <div class="text-center">
                        <button class="btn btn-link"
                                onclick="this.parentNode.querySelector('input[type=number]').stepDown()">
                            <i class="fas fa-minus"></i>
                        </button>
                        {{ item.update_quantity_form.quantity }}
                        <button class="btn btn-link"
                                onclick="this.parentNode.querySelector('input[type=number]').stepUp()">
                            <i class="fas fa-plus"></i>
                        </button>
                    </div>
                    {{ item.update_quantity_form.update }}
                    {% csrf_token %}
                </form>
            </div>
            <div class="col-md-1 justify-content-center">
                <div class="text-center">{{ item.price }}</div>
            </div>
            <div class="col-md-2 justify-content-center">
                <div class="text-center">{{ item.total_price }}</div>
            </div>
            <div class="col-md-1 justify-content-center">
                <div class="text-center">
                    <a href="{% url 'cart:cart_remove' product.id %}" style="color:red;"><i
                            class="fa fa-trash red-color" aria-hidden="true"></i></a>
                </div>
            </div>
        </div>
    </div>
</div>
{% endwith %}
{% endfor %}
<div class="row col-md-12 p-3">
    <div class="col col-md-12 text-center">ОФОРМЛЕНИЕ ЗАКАЗА <i class="fa fa-shopping-cart green-color"
                                                                aria-hidden="true"></i></div>
</div>

<div class="card mb-5">
    <div class="card-body p-4">
        <form action="{% url 'orders_add' %}" method="post">
            <div class="row col-md-12">
                <div class="col col-md-6">
                    <div class="d-flex flex-row pb-3">
                        <div class="d-flex align-items-center pe-2">
                            <input class="form-check-input" type="radio" name="radioNoLabel" id="radioNoLabel1v"
                                   value="1" aria-label="" checked/>
                        </div>
                        <div class="rounded border w-100 p-3">
                            <div class="d-flex align-items-center mb-0">
                                <i class="fab fa-cc-mastercard fa-2x text-dark pe-2"></i>
                                <div class="pay ml-2"> Оплата по QR коду</div>

                            </div>
                        </div>
                    </div>
                    <div class="d-flex flex-row pb-3">
                        <div class="d-flex align-items-center pe-2">
                            <input class="form-check-input" type="radio" name="radioNoLabel" id="radioNoLabel2v"
                                   value="2" aria-label=""/>
                        </div>
                        <div class="rounded border w-100 p-3">
                            <div class="d-flex align-items-center mb-0">
                                <i class="fab fa-cc-visa fa-2x fa-lg text-dark pe-2"></i>
                                <div class="pay ml-2">Оплата при получении</div>
                            </div>

                        </div>
                    </div>
                </div>
                <div class="col col-md-6">
                    <div class="row">
                        <div class="col col-md-6 p-2">Стоимость заказа:</div>
                        <div class="col col-md-6 p-2"><input class="form-control" type="text"
                                                             placeholder="{{ cart.get_total_price }}" name="total_price"
                                                             id="total_price"
                                                             value="{{ cart.get_total_price }}"
                                                             readonly></div>

                        <div class="col col-md-6 p-2">Фамилия и имя:</div>
                        <div class="col col-md-6 p-2"><input class="form-control"
                                                             placeholder="{{user.last_name}} {{user.first_name}}"
                                                             id="user"
                                                             name="user" readonly></div>
                        <div class="col col-md-6 p-2">Адрес доставки:</div>
                        <div class="col col-md-6 p-2"><input class="form-control"
                                                             placeholder="Ваш адрес"
                                                             id="address"
                                                             name="address" required>
                        </div>
                    </div>
                </div>
                <input class="form-control" hidden="hidden"
                       name="user" id="{{user.id}}">
            </div>
            <div class="row col-md-12">
                <div class="col col-md-12">
                    <div class="text-center">
                        <button type="submit" class="btn btn-outline-success">Оформить заказа</button>
                    </div>
                </div>
            </div>
            {% csrf_token %}
        </form>
    </div>
</div>

{% else %}
<div class="row col-md-12 p-5">
    <div class="col col-md-12 text-center">
        <h1>Корзина пуста</h1>
    </div>
</div>
{% endif %}

{% endblock %}